server:
  port: 18080

## Dubbo 服务提供者配置
spring:
  application:
    name: demo-provider # provider应用名称

# Dubbo组件扫描的基础包
dubbo:
  scan:
    base-packages: com.da.demoprovider
  application:
    name: demo-provider  # Dubbo应用程序名称
  protocol:       #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
    name: dubbo   # Dubbo 协议与端口
    port: 20888
  registry:       # Dubbo 注册地址
    address: zookeeper://127.0.0.1:2181
  metadata-report:
    address: zookeeper://127.0.0.1:2181

